env:
  global:
  - TERM=dumb

language: java
jdk: openjdk8

addons:
  apt:
    update: true
    packages:
    - bash
    - curl
    - libxml2-utils
    - libappindicator1
    - fonts-liberation
    - google-chrome-stable
    - docker-ce

install: true
before_install:
- nvm install lts/*
- export CHROME_BIN=/usr/bin/google-chrome
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 8080 80
- sudo add-apt-repository universe -y
- sudo apt-get update -yqq
- sudo apt-get install -yqq --no-install-suggests --no-install-recommends tree jq python-pip
- sudo pip install docker-compose httpie >/dev/null 2>&1

script:
- ./gradlew clean build -b grpc-server/build.gradle
- ./gradlew clean build -b grpc-client/build.gradle
- java -jar grpc-server/build/libs/*jar &
- java -jar grpc-client/build/libs/*jar &
- wait_for 8000 8080 8081
- http get :8081 name=Gradle emo=SAD
- http get :8081 name=Gradle emo=HAPPY
- stop_any 8000 8080 8081

- ./mvnw clean package -U -f grpc-server/pom.xml
- ./mvnw clean package -U -f grpc-client/pom.xml
- java -jar grpc-server/target/*jar &
- java -jar grpc-client/target/*jar &
- wait_for 8000 8080 8081
- http get :8081 name=Maven emo=SAD
- http get :8081 name=Maven emo=HAPPY
- stop_any 8000 8080 8081

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
  - $HOME/.docker
